# Generated by Django 5.2.1 on 2025-06-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_service_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Administrator')], default='customer', max_length=10),
        ),
    ]
