# Generated by Django 5.2.1 on 2025-06-02 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoWash Hub', max_length=100)),
                ('site_description', models.TextField(default='Your premier car wash service provider')),
                ('contact_email', models.EmailField(default='contact@autowashhub.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('business_hours', models.TextField(default='Monday-Friday: 8:00 AM - 6:00 PM\nSaturday: 9:00 AM - 5:00 PM\nSunday: Closed')),
                ('address', models.TextField(default='123 Main Street\nAnytown, ST 12345')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('enable_dark_mode', models.BooleanField(default=False)),
                ('booking_interval', models.IntegerField(default=30, help_text='Booking time interval in minutes')),
                ('min_advance_booking', models.IntegerField(default=2, help_text='Minimum hours in advance for booking')),
                ('max_advance_booking', models.IntegerField(default=30, help_text='Maximum days in advance for booking')),
                ('max_daily_bookings', models.IntegerField(default=20, help_text='Maximum bookings allowed per day')),
                ('allow_same_day_booking', models.BooleanField(default=True)),
                ('require_payment', models.BooleanField(default=False)),
                ('notify_new_booking', models.BooleanField(default=True)),
                ('notify_cancelled_booking', models.BooleanField(default=True)),
                ('notify_new_user', models.BooleanField(default=True)),
                ('send_booking_confirmation', models.BooleanField(default=True)),
                ('send_booking_reminder', models.BooleanField(default=True)),
                ('reminder_hours', models.IntegerField(default=24, help_text='Hours before appointment to send reminder')),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
